### ISSUE TITLE
THIS EFI SUPPORT MACOS 13

### ISSUE THREAD

**Issue by iverycd** [aryapramudika/Hackintosh-E490#1]
HI,DOES THIS EFI WORK FINE ON MACOS 13?

**Comment by theking988** [comment]
Does the battery can working well?

**Comment by aryapramudika** [comment]
> HI,DOES THIS EFI WORK FINE ON MACOS 13?

I haven't tried it yet, in this EFI i use Monterey

**Comment by aryapramudika** [comment]
> Does the battery can working well?

working well? indicator is working, but the optimize battery i don't know. you can try it and give feedback here

**Comment by iverycd** [comment]
> > HI,DOES THIS EFI WORK FINE ON MACOS 13?
> 
> I haven't tried it yet, in this EFI i use Monterey

THQ,I UPGRAGE YOUR EFI TO OC 0.8.7 AND IT WORK FINE ON MACOS 13.1,BLUETOOTH CAN WORK FINE,BUT WIFI CAN NOT USE

**Comment by iverycd** [comment]
[](url)

> 

MY THINKPAD E490 USE THIS EFI WORK FINE WITH BATTERY,AND ALSO WORK FINE ON OC0.8.7 MACOS 13,1

**Comment by iverycd** [comment]
> Does the battery can working well?

MY THINKPAD E490 USE THIS EFI WORK FINE WITH BATTERY,AND ALSO WORK FINE ON OC0.8.7 MACOS 13,1
